title: Tnaito Note
author: tnaito
email: 42tnaito@gmail.com
description: >
  memo tech ...
baseurl: ""
url: "https://naito-tomoki.github.io/"

markdown: kramdown
theme: minima

timezone: Asia/Tokyo

future: true
